export { default as Portafolio} from "./Portafolio"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as SEO1 } from "./seo1"
export { default as Bio } from "./Bio"
export { default as Layoutblog } from "./layoutblog" 
export { default as ImagePortafolio } from "./imageportafolio"
export { default as Proyectos } from "./Proyectos"
export { default as ImageExperiencia } from "./imageexperiencia"
export { default as Experiencia } from "./Experiencia"
export { default as Habilidades } from "./Habilidades"
export { default as Hobbies } from "./Hobbies"
export { default as ImageHobbies } from "./imagehobbies"
export { default as PhotoBirds } from "./PhotoBirds"
export { default as Acerca } from "./Acerca"